# Site settings
title: Nikol's Kitchen 
description: "Since you're here, might as well make use of your time and learn something new...Oh and follow me @kolma3nikol"
author: "Nikol"

baseurl: "/nicools-kitchen"
url: "https://AntiLibrary5.github.io" #"https://your-username.github.io"

# Build settings
theme: minima # We can start with a basic theme and override it with our CSS
markdown: kramdown