# Site settings
title: I go by @ Kolma3nikol 
description: "Since you're here, might as well make use of your time and learn something new"
author: "Nikol"

baseurl: "/nicools-kitchen"
url: "https://AntiLibrary5.github.io" #"https://your-username.github.io"

# Build settings
theme: minima # We can start with a basic theme and override it with our CSS
markdown: kramdown