# Site settings
title: Nikool's Kitchen
description: "Quick bites and cozy delights from a home kitchen."
author: "Nikool"

baseurl: "/nicools-kitchen"
url: "https://AntiLibrary5.github.io" #"https://your-username.github.io"

# Build settings
theme: minima # We can start with a basic theme and override it with our CSS
markdown: kramdown